[2022-12-26 20:19:19,467] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: podcast_summary2.download_episodes manual__2022-12-26T20:19:17.010421+00:00 [queued]>
[2022-12-26 20:19:19,476] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: podcast_summary2.download_episodes manual__2022-12-26T20:19:17.010421+00:00 [queued]>
[2022-12-26 20:19:19,476] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-26 20:19:19,477] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-26 20:19:19,477] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-26 20:19:19,491] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): download_episodes> on 2022-12-26 20:19:17.010421+00:00
[2022-12-26 20:19:19,495] {standard_task_runner.py:52} INFO - Started process 1403 to run task
[2022-12-26 20:19:19,498] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'podcast_summary2', 'download_episodes', 'manual__2022-12-26T20:19:17.010421+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/podcast_summer/podcast_summer2.py', '--cfg-path', '/tmp/tmpjcwttxhm', '--error-file', '/tmp/tmpi52m046w']
[2022-12-26 20:19:19,499] {standard_task_runner.py:80} INFO - Job 14: Subtask download_episodes
[2022-12-26 20:19:19,550] {task_command.py:369} INFO - Running <TaskInstance: podcast_summary2.download_episodes manual__2022-12-26T20:19:17.010421+00:00 [running]> on host b1dad8c5c2ae
[2022-12-26 20:19:19,632] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=podcast_summary2
AIRFLOW_CTX_TASK_ID=download_episodes
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T20:19:17.010421+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-26T20:19:17.010421+00:00
[2022-12-26 20:19:19,633] {logging_mixin.py:115} INFO - Downloading a-little-more-inflation-here-a-little-less-there.mp3
[2022-12-26 20:19:21,925] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/podcast_summer/podcast_summer2.py", line 70, in download_episodes
    with open(audio_path, "wb+") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'episodes/a-little-more-inflation-here-a-little-less-there.mp3'
[2022-12-26 20:19:21,940] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=podcast_summary2, task_id=download_episodes, execution_date=20221226T201917, start_date=20221226T201919, end_date=20221226T201921
[2022-12-26 20:19:21,951] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task download_episodes ([Errno 2] No such file or directory: 'episodes/a-little-more-inflation-here-a-little-less-there.mp3'; 1403)
[2022-12-26 20:19:21,958] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-26 20:19:21,983] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
